#!/bin/bash
set -eu
#set -x

JWT_USER_PATH=${JWT_USER_PATH:-}
if [ -z "$JWT_USER_PATH" ]; then
    uid=`id -u`
    JWT_USER_PATH="/tmp/jwt_user_u${uid}/token.jwt"
fi

if [ "${GFARM_SASL_USER:-}" = "anonymous" ]; then
    # SASL ANONYMOUS
    curl "$@"
elif [ -n "${GFARM_SASL_USER:-}" -a -n "${GFARM_SASL_PASSWORD:-}" ]; then
    #pass=`echo -n "${GFARM_SASL_USER}:${GFARM_SASL_PASSWORD}" | base64`
    #curl -H "Authorization: Basic ${pass}" "$@"
    curl -u "${GFARM_SASL_USER}:${GFARM_SASL_PASSWORD}" "$@"
elif [ -f "$JWT_USER_PATH" ]; then
    token=`cat "$JWT_USER_PATH"`
    headers=()
    headers+=("-H" "Authorization: Bearer ${token}")
    curl "${headers[@]}" "$@"
else
    echo >&2 "Error: Environment variable JWT_USER_PATH (or, GFARM_SASL_USER and GFARM_SASL_PASSWORD) is required"
    exit 1
fi
